Update changelog
indeni/cloudrail-demo pull request #4
Opened 2020-09-28 03:56 UTC by charlesk92

Adding changelog for v0.1

2020-09-28 16:25 UTC, random930 requested changes

2020-09-28 16:25 UTC, random930 commented on CHANGELOG.md
> +## [0.1.0] - (September 22, 2020)
I think we need to have versioning done more granularly. It's actually version 0.1.213 right now. We can expect more knowledge, bug fixes, features, etc. in the build numbers.

2020-09-28 17:00 UTC, cysk92 commented on CHANGELOG.md
> +## [0.1.0] - (September 22, 2020)
Updated the date. We'll need to start thinking about when is the right time to provide release notes as we will be making incremental changes for each minor release.

2020-09-28 17:50 UTC, random930 commented
@charlesk92 your update makes sense. We may want to wait with releasing the CHANGELOG until the release is in prod.

2020-09-29 06:32 UTC, Alon-Ashkenazi-Indeni approved these changes

2020-09-29 15:16 UTC, random930 approved these changes

2020-10-01 18:35 UTC, merged